server.port: 7003

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  datasource:
    url:  jdbc:mysql:http://localhost:3306/inventory?useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
