server:
  port: 7001
management:
  endpoints:
    web:
      exposure:
        include: *
spring:
  datasource:
    url:  jdbc:mysql:http://localhost:3306/level_up?useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
